from typing import Optional
from sqlmodel import Field, SQLModel


class Hero(SQLModel, table=True):
    # id is optional because it generated by the db, not this code
    id: Optional[int] = Field(default=None, primary_key=True)
    name: str = Field(index=True)  # creates an index for Hero.name entries for easier
    secret_name: str
    age: Optional[int] = Field(default=None, index=True)

